adkiller/control/urls.py
# -*- coding: utf-8 -*-
"""
Urls for app control
"""

from django.conf.urls import patterns, url

from adkiller.control.views import as_run
from adkiller.control.views import programacion_dtv
from adkiller.control.views import metricas_diarias_user
from adkiller.control.views import control_tandas
from adkiller.control.views import alerta_falla_video

urlpatterns = patterns(
    '',
    url(r'^as_run', as_run),
    url(r'^programacion_dtv', programacion_dtv),
    url(r'^metricas/', metricas_diarias_user),
    url(r'^tandas/', control_tandas),
    url(r'^vnod/', alerta_falla_video), # vnod: video no descarga
)

adkiller/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template

from longerusername.forms import AuthenticationForm
from django import forms


class AuthForm(AuthenticationForm):
    username = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = None
        self.fields['username'].max_length = 120


import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from app.api import *
from home.views import root
from app.views import home, exportar_programas, exportar_marcas
from ratings.views import upload_ratings

emisiones = Api(api_name='emisiones')
emisiones.register(ProgramaResource())
emisiones.register(ProductoResource())
emisiones.register(EmisionResource())
emisiones.register(HorarioResource())
emisiones.register(CiudadResource())
emisiones.register(MedioResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'adkiller.views.home', name='home'),
    # url(r'^adkiller/', include('adkiller.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/exportar_programas', exportar_programas),
    url(r'^api/exportar_marcas', exportar_marcas),
    (r'^api/', include(emisiones.urls)),
    (r'^app/', include('adkiller.app.urls')),
    (r'^decos/', include('adkiller.decos.urls')),
    (r'^material/', include('adkiller.material.urls')),
    (r'^home/', include('adkiller.home.urls')),
    (r'^social/', include('adkiller.social.urls')),
    (r'^filtros/', include('adkiller.filtros.urls')),
    (r'^informes/', include('adkiller.informes.urls')),
    (r'^usuarios/', include('adkiller.usuarios.urls')),
    (r'^adtrack/', include('adkiller.adtrack.urls')),
    (r'^control/', include('adkiller.control.urls')),
    (r'^apis/', include('adkiller.apis.urls')),
    (r'^media_map/', include('adkiller.media_map.urls')),
    url(r'^$', root, name='root'),
    (r'^autocomplete/', include('autocomplete_light.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',  {'authentication_form': AuthForm}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^accounts/register/$','adkiller.usuarios.views.register'),
    (r'^estado_server/(?P<server>\w+)/','adkiller.app.views.estado_server'),
    (r'^estado_server/','adkiller.app.views.estado_servers'),
    (r'^accounts/register_ok/(?P<usuario>\d+)/','adkiller.usuarios.views.register_ok'),
    (r'^dowser/', include('django_dowser.urls')),

    (r'^thankyou/', direct_to_template, {'template': 'thankyou_page.html','extra_context':{'settings':settings}}),
    (r'^propuesta/', direct_to_template, {'template': 'landing_propuesta.html','extra_context':{'settings':settings}}),
    (r'^accounts/login_demo/$', 'django.contrib.auth.views.login',{'template_name': 'registration/login_demo.html', 'authentication_form': AuthForm, 'extra_context':{'settings':settings}}),

    # archivos especiales
    (r'^jwplayer/jwplayer\.js$', 'django.views.generic.simple.redirect_to', {'url': '/static/js/player/jwplayer.js', 'permanent': True}),
    (r'^jwplayer/jwplayer\.html5\.js$', 'django.views.generic.simple.redirect_to', {'url': '/static/js/player/jwplayer.html5.js', 'permanent': True}),
    (r'^jwplayer/jwplayer\.flash\.swf$', 'django.views.generic.simple.redirect_to', {'url': '/static/js/player/jwplayer.flash.swf', 'permanent': True}),
    (r'^googledae215d9eaff8abb\.html$', 'django.views.generic.simple.redirect_to', {'url': '/static/googledae215d9eaff8abb.html'}),
    (r'^google2f37b16a81f0f6e7\.html$', 'django.views.generic.simple.redirect_to', {'url': '/static/google2f37b16a81f0f6e7.html'}),
    (r'^sitemap\.xml$', 'django.views.generic.simple.redirect_to', {'url': '/static/home/sitemap.xml'}),
    (r'^robots\.txt$', 'django.views.generic.simple.redirect_to', {'url': '/static/home/robots.txt'}),
    (r'^htaccess\.txt$', 'django.views.generic.simple.redirect_to', {'url': '/static/home/htaccess.txt'}),
    (r'^ratings/', upload_ratings),



) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    url(r'^mediamap/static/(?P<path>.*)$',  'django.views.static.serve', {'document_root': settings.MEDIAMAP_ROOT}),
]

urlpatterns += staticfiles_urlpatterns()

#Para detectar memory leaks:
#import guppy
#from guppy.heapy import Remote
#Remote.on()


#DEBUG TOOLBAR: ejecutarlo con servidor de desarrollo de django
#DEBUG_TOOLBAR_PATCH_SETTINGS = False
#INTERNAL_IPS = ["174.37.209.218", "127.0.0.1"]
#from django.conf.urls import include, patterns, url
#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += patterns('',
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    )

adkiller/control/models.py
# -*- coding: utf-8 -*-
# pylint: disable=fixme, too-many-arguments, redundant-keyword-arg
# pylint: disable=old-style-class
"""
Models for app control
"""

# python imports
from datetime import timedelta

# django imports
from django.db import models
from django.contrib.auth.models import User
from django.contrib.admin.models import LogEntry

# project imports
from adkiller.app.models import Emision
from adkiller.app.models import Medio
from adkiller.app.models import Soporte
from adkiller.media_map.models import Formato
from adkiller.media_map.models import TipoSegmento

class MetricasGrab(models.Model):
    """..."""
    # MUESTRA:
    # el dia que se esta midiendo
    fecha = models.DateField()
    # es el conjunto de canales que se esta midiendo
    media_pack = models.ForeignKey(Soporte, null=True, blank=True)

    # GRABACION:
    # son los que tienen servidor de grabacion, es decir,
    # los que se piensan grabar
    medios = models.IntegerField()
    # son los que no tienen pérdida de material en ese dia
    medios_grabados = models.IntegerField()
    # son los que cumplen los requerimientos mínimos
    # (imagen en color, con audio, etc)
    medios_en_calidad_estandar = models.IntegerField()

    # para llenar con datos viejos, primero hay que
    # definir la fecha y media_pack
    def calculate_old(self):
        """..."""
        self.medios = Emision.objects.filter(
            fecha=self.fecha,
            horario__medio__soporte=self.soporte
        ).values("horario__medio").distinct().count()

    # para llenar con datos de ayer, primero hay que
    # definir el media_pack
    def calculate(self):
        """..."""
        self.medios = Medio.objects.filter(
            server_grabacion__isnull=False,
            soporte=self.soporte
        )


class MetricasProc(models.Model):
    """..."""
    # SOLO DESPUES DE 72 hs

    # MUESTRA:
    # el dia que se esta midiendo
    fecha = models.DateField()
    # es el conjunto de canales que se esta midiendo
    media_pack = models.ForeignKey(Soporte, null=True, blank=True)


    # PROCESAMIENTO:
    # cantidad de registros
    registros_infoad = models.IntegerField()
    # cantidad de horas que se aplicaron para generar esos registros
    horas_aplicadas_infoad = models.IntegerField()

    def calculate(self):
        """..."""
        self.registros_infoad = Emision.objects.filter(
            fecha=self.fecha,
            horario__medio__soporte=self.media_pack
        ).count()
        # FIXME
        self.horas_aplicadas_infoad = 10


class MetricasUser(models.Model):
    """..."""

    # MUESTRA:
    # el dia que se esta midiendo
    fecha = models.DateField()

    # USUARIOS
    # cantidad de nuevos usuarios en el dia
    nuevos_prospectos_infoad = models.IntegerField()
    # cantidad de logins en el dia
    ingresos_infoad = models.IntegerField()


    def calculate(self):
        """..."""
        tomorrow = self.fecha + timedelta(days=1)
        self.nuevos_prospectos_infoad = User.objects.filter(
            date_joined__gte=self.fecha,
            date_joined__lt=tomorrow
        ).count()
        self.ingresos_infoad = LogEntry.objects.filter(
            action_flag=5,
            action_time__gte=self.fecha,
            action_time__lt=tomorrow
        ).count()


class MetricaDiariaUser(models.Model):
    """Clase para medir performance diaria
    de un usuario en la carga de patrones"""

    BLANK = 0
    CARGA_PATRON_IMAGEN = 1
    CARGA_PATRON_AUDIO = 2
    REGISTRO = 3
    EDICION = 4
    CONTROLANDO = 5
    CERRANDO = 6
    NAVEGACION = 6

    ACCION_CHOICES = (
        (BLANK, u''),
        (CARGA_PATRON_IMAGEN, u'Carga patrón imágen'),
        (CARGA_PATRON_AUDIO, u'Carga patrón audio'),
        (REGISTRO, u'Registro de datos'),
        (EDICION, u'Actualización de datos'),
        (NAVEGACION, u'Navegación'),
    )

    fecha = models.DateField()
    fecha_material = models.DateField(null=True)
    user = models.ForeignKey(User)
    medio = models.ForeignKey(Medio)
    tipo_segmento = models.ForeignKey(TipoSegmento)
    formato = models.ForeignKey(Formato, null=True)
    cantidad = models.IntegerField()
    material = models.IntegerField(null=True)
    duracion = models.FloatField()
    accion = models.SmallIntegerField(choices=ACCION_CHOICES, default=REGISTRO)


    def to_string(self):
        """Devolver str resumen"""
        tpl = '\n----------------------------------------------------------\n'
        tpl += u'Métrica {self.fecha} - {self.user.username} - {self.medio}\n'
        tpl += 'TIPO: {self.tipo_segmento} '
        if self.formato:
            tpl += 'FORMATO: {self.formato:10} '
        tpl += '\n'
        tpl += ('ACCION: {accion}\n'
                'CANTIDAD: {self.cantidad} '
                'TIEMPO: {self.duracion:.1f} segundos')
        tpl += '\n-----------------------------------------------------------'
        return tpl.format(self=self,
                          accion=[desc for (ac, desc) in self.ACCION_CHOICES
                                  if ac == self.accion][0])

    def get_accion_as_string(self):
        """Devolver string según el tipo de accion"""
        for choice in self.ACCION_CHOICES:
            if self.accion == choice[0]:
                return choice[1]
        # no debería llegar acá
        return u'Acción desconocida'

class Navigation(models.Model):
    """Clase para medir el tiempo
    que un usuario emplea en mediamap"""

    NM_CONTROLANDO = 0
    NM_CERRANDO = 1

    class Meta:
        """'Enforzar' clave candidata"""
        unique_together = (
            ('user', 'medio', 'inicio'),
        )

    NAVIGATION_MODE = (
        (NM_CONTROLANDO, u'Controlando'),
        (NM_CERRANDO, u'Cerrando'),
    )
    user = models.ForeignKey(User)
    medio = models.ForeignKey(Medio)
    desde_thumb = models.DateTimeField()
    hasta_thumb = models.DateTimeField()
    inicio = models.DateTimeField()
    fin = models.DateTimeField()

    # acción que se hizo luego de hacer esta navegación
    accion_destino = models.ForeignKey(MetricaDiariaUser, null=True, blank=True)

    modo = models.SmallIntegerField(choices=NAVIGATION_MODE,
                                    default=NM_CONTROLANDO)
    capas_activas = models.ManyToManyField(TipoSegmento)

adkiller/control/forms.py
# -*- coding: utf-8 -*-
"""
Forms para app control
"""
from datetime import datetime

from django import forms
from django.contrib.auth.models import User
from django.forms.extras.widgets import SelectDateWidget

from adkiller.app.models import Medio
from adkiller.media_map.models import TipoSegmento

class AsRunForm(forms.Form):
    """As run form"""
    medio = forms.ModelChoiceField(
        Medio.objects.filter(
            soporte__nombre__in=[
                'Televisión',
                'TV Aire',
                'TV Cable',
                'TV Paga',
                'Tv Satelital'
            ]
        )
    )
    archivo = forms.FileField()
    inverso = forms.BooleanField(initial=False, required=False)
    crear_emisiones_no_encontradas = forms.BooleanField(initial=False,
                                                        required=False)

class MetricasDiariasUserForm(forms.Form):
    """Formulario para consultar métricas diarias"""
    desde = forms.DateField(initial=datetime.now().date(),
                            widget=SelectDateWidget)
    hasta = forms.DateField(initial=datetime.now().date(),
                            widget=SelectDateWidget)

    users = User.objects.filter(
        is_staff=True,
        is_active=True
    ).exclude(username='root').order_by('username')
    filtrar_por_usuario = forms.ModelChoiceField(required=False, queryset=users)
    ACCION_CHOICES = (
        (0, u''),
        (1, u'Carga patrón imágen'),
        (2, u'Carga patrón audio'),
        (3, u'Registro de datos'),
        (4, u'Actualización de datos'),
    )
    filtrar_por_accion = forms.ChoiceField(required=False,
                                           widget=forms.Select(),
                                           choices=ACCION_CHOICES)

    segmentos = TipoSegmento.objects.all().exclude(
        nombre='Material').exclude(
        nombre__contains='Navigation').exclude(
        nombre='Bache-IFEP')
    filtrar_por_tipo_de_segmento = forms.ModelChoiceField(segmentos,
                                                          required=False)

    medios = Medio.objects.all().exclude(soporte__nombre='Revista')
    medios = medios.exclude(soporte__nombre='Diario')
    medios = medios.exclude(soporte__nombre='Diarios Capital')
    medios = medios.exclude(soporte__nombre='Diarios Interior')

    filtrar_por_medio = forms.ModelChoiceField(queryset=medios, required=False)

adkiller/control/templates/as_run.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Comparaci&oacute;n AS RUN</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="static/js/main.js"></script>
        <script type="text/javascript">
            $(function () {
                    $("#id_inverso").click(function () {
                        if ($("#id_inverso").is(':checked'))
                            $("#id_crear_emisiones_no_encontradas").parent().hide();
                        else
                            $("#id_crear_emisiones_no_encontradas").parent().show();
                    });
            });

            function loading(form)
            {
                //var loading_div = document.getElementById('loading');
                $('#loading').html('<h1 id="msg">Su archivo se está procesando, esto puede tomar varios minutos</h1>');
                return true;
            }
        </script>
    </head>
    <body>
        <div  id="header">
            <img id="logoAsRun" src="/static/img/logo.png">
            <h1><center>Comparaci&oacute;n AS RUN</center></h1>
        </div><!-- fin conatiner header-->
        <div class="principal">
                    <div id="atencion">
                        <h2 id="tituloAtencion">Atención:</h2>
                        <ul id="listaGeneral">
                            <h4 id="tituloAsegurese">Asegúrese de que su archivo cumple con los siguientes requisitos</h4>
                            <ul id="itemsPrincipales">
                                <li>FORMATO: csv</li>
                                <li>COLUMNAS:</li>
                                <ul id="itemsSecundarios">
                                    <li>ID (dtv) <sup>&Dagger;</sup></li>
                                    <li>Marca <sup>&Dagger;</sup></li>
                                    <li>Producto <sup>&Dagger;</sup></li>
                                    <li>Spotname</li>
                                    <li>Status <sup>*</sup></li>
                                    <li>Fecha</li>
                                    <li>Hora</li>
                                    <li>Duración <sup>*</sup></li>
                                    <li>Programa <sup>*</sup></li>
                                </ul><!-- fin ul itemsSecundarios -->
                            </ul><!-- fin ul itemsPrinsipales -->
                        </ul><!-- fin ul listaGeneral -->
                        <p>* No se usan actualmente.</p>
                        <p>&Dagger; Se puede controlar por A# o por Marca y Producto.
                            <ul>
                                <li>Si se encuentra una columna con el A# no se
                                    usar&aacute;n Marca ni Producto.</li>
                                <li>Si no se incluye #A, es obligatorio incluir
                                    Marca y Producto.</li>
                                <li>Marca y Producto deben coincidir plenamente con los de Infoad.</li>
                            </ul>
                        </p>
                    </div>

                <div class="contFormGeneral">
                    <h3 id="tituloForm">Subir archivo a comparar</h3>
                    <hr>
                    <form name="as_run_file" action="/control/as_run/" method="POST" onsubmit="return loading(this);" enctype="multipart/form-data" id="form">
                            {% csrf_token %}
                            <table>
                                {{form.as_p}}
                                <tr>
                                    <td></td>
                                    <td>
                                        <button class="btn btn-default btn-block" type="submit" id="btnCompara">Comparar</button>
                                    </td>
                                </tr>
                             </table><!-- fin table -->
                    </form><!-- fin form -->
                </div><!--fin cont general-->
        </div><!-- fin container-->
        <div class="container" id="contLoading">
            <div class="row">
                <div class="col-md-12">
                    <div id="loading" style="font-size: 2em; color: red;">
                    </div><!-- fin loading -->
                </div>
            </div>
        </div><!-- fin contLoading -->
    </body>
</html>

adkiller/control/templates/map.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="30" />
    <title>Métricas de Infoxel</title>
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script type="text/javascript" src="/static/js/maplabel-compiled.js"></script>

    <script>

  var titulo = new google.maps.LatLng(-10.924830, -105.131428);

  var argentina = new google.maps.LatLng(-31.417760, -67.184783);
  var bolivia = new google.maps.LatLng(-15.924830, -65.131428);
  var brasil = new google.maps.LatLng(-13.3129747, -53.6609157);
  var chile = new google.maps.LatLng( -28.609499, -71.671171);
  var colombia = new google.maps.LatLng(2.6131841, -77.2377539);
  var paraguay = new google.maps.LatLng(-24.034723, -58.758572);
  var peru = new google.maps.LatLng(-12.296301, -75.718817);
  var venezuela = new google.maps.LatLng(5.804740, -66.118772);
  



function crear_label(text, pos, map) {
  var mapLabel = new MapLabel({
           text: text,
           position: pos,
           map: map,
           fontSize: 20,
           align: 'left',
           fontColor: '#FF0000'
  });


}




function initialize() {
  

  var mapOptions = {
    zoom: 4,
    center: bolivia,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }

  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  /*  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Hello World!'
  });
  */

  crear_label("{{ titulo }}", titulo, map);
  crear_label("{{ valores.argentina }}", argentina, map);
  crear_label("{{ valores.brasil }}", brasil, map);
  crear_label("{{ valores.chile }}", chile, map);
  crear_label("{{ valores.colombia }}", colombia, map);
  crear_label("{{ valores.paraguay }}", paraguay, map);
  crear_label("{{ valores.peru }}", peru, map);
  crear_label("{{ valores.venezuela }}", venezuela, map);

}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>
  <body>
    <div id="map-canvas"></div>
  </body>
</html>

adkiller/control/templates/metricas_diarias_user.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">

        <title>M&eacute;tricas diarias</title>
        <style>
          #principal {
              margin: 2px 0px;
              background-color: #DDD;
              padding: 10px 20px;
          }
          #form {
              background-color: #DDD;
              padding: 10px 20px;
              margin: 2px 0px;
          }
          #tabla {
              background-color: #DDD;
              padding: 10px 20px;
              margin: 2px 0px;
          }
          #header {
              background-color: #DDD;
              padding: 10px 20px;
              margin: 2px 0px;
          }
          #results {
              background-color: #DDD;
              padding: 10px 20px;
              margin: 2px 0px;
          }
          #error {
              color: red;
              padding: 10px 20px;
              margin: 2px 0px;
          }
          #button{
            color: #333;
            background-color: #99F;
          }
        </style>
    </head>
    <body>
        <div id="header">
            <h1><center>M&eacute;tricas diarias</center></h1>
        </div><!-- fin conatiner header-->
        <div id="form">
            <form name="metricas_diarias" action="/control/metricas/" method="POST" id="form">
                {% csrf_token %}
                <table>
                    <b>Seleccione un período</b><br>
                    {{form.as_table}}
                    <tr>
                        <td></td>
                        <td>
                            <br>
                            <button class="btn btn-default btn-block" type="submit" id="btn_submit">Mostrar m&eacute;tricas</button>
                        </td>
                    </tr>
                </table><!-- fin table -->
            </form><!-- fin form -->
        </div><!--fin div form -->
        <div id="results">
            <center id="mytable">
            {% if error %}
                <div id="error">
                  <p>{{ error }}</p>
                <div>
            {% else %}
                {% if metricas_table %}
                    {% autoescape off %}
                    {{ metricas_table }}
                    {% endautoescape %}
                {% endif %}
            {% endif %}
            </center>
            <div align="right">
                {% if metricas_table %}
                    <br>
                    <button onClick="doCsv()" id="button"><img src="{{STATIC_URL}}/img/excel.png" class="alt"/> Descargar Excel</button>
                {% endif %}
                <script type="text/javascript">
                function doCsv() {
                    var table = document.getElementById('mytable').innerHTML;
                    var data = table.replace(/&amp;/g, '&')
                        .replace(/<thead style="">/g, '')
                        .replace(/<\/thead>/g, '')
                        .replace(/<tbody style="">/g, '')
                        .replace(/<\/tbody>/g, '')
                        .replace(/<table style="background-color: #EEE;">/g, '')
                        .replace(/<\/table>/g, '')
                        .replace(/<tr style="background-color: #DDD;">/g, '')
                        .replace(/<tr style="">/g, '')
                        .replace(/<\/tr>/g, '\r\n')
                        .replace(/<th style="background-color: #BBB; padding: 10px 4px; margin: 2px 0px 2px 0px;">/g, '')
                        .replace(/<\/th>/g, ';')
                        .replace(/<td style="padding: 4px">/g, '')
                        .replace(/<\/td>/g, ';')
                        .replace(/\t/g, '')
                        .replace(/\n/g, '');
                    /* esto anda solo en chrome
                    var link = document.createElement('a');
                    link.download = 'metricas.csv';
                    link.href = "data:text/csv;charset=utf-8," + encodeURI(data);
                    link.click();
                    console.log(link);
                    */
                    var encoded_uri = "data:text/csv;filename=download.csv,charset=utf-8," + encodeURI(data);
                    window.open(encoded_uri);
                }
                </script>
            </div>
            </div>
    </body>
</html>

adkiller/control/templates/tandas.html
<!doctype html>
<html lang="es">
  <head>
  </head>
  <body>
    <h1>Control de Tandas</h1>
    {% for medio in medios %}
      <h2>{{ medio.nombre }}</h2>
      {% if medio.tandas %}
        <h3>Tandas</h3>
        <p>{{ medio.total }} tanda{{ medio.total|pluralize }} - {{ medio.auto }} % automáticas</p>
      {% endif %}
      {% if medio.baches %}
        <h3>Baches</h3>
        {% for bache in medio.baches %}
          <p>{{ bache.desde}} - {{bache.hasta }}</p>
        {% endfor %}
      {% endif %}
      <hr>
    {% endfor %}
  </body>
</html>