adkiller/material/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from views import MainView, download_file
from django.contrib.auth.decorators import login_required
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', MainView.as_view(), name='material_home'),
    url(r'^download/(?P<params>.*)/$', download_file, name='material_download_file'),
    #login_required()
)

adkiller/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.simple import direct_to_template

from longerusername.forms import AuthenticationForm
from django import forms


class AuthForm(AuthenticationForm):
    username = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = None
        self.fields['username'].max_length = 120


import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from app.api import *
from home.views import root
from app.views import home, exportar_programas, exportar_marcas
from ratings.views import upload_ratings

emisiones = Api(api_name='emisiones')
emisiones.register(ProgramaResource())
emisiones.register(ProductoResource())
emisiones.register(EmisionResource())
emisiones.register(HorarioResource())
emisiones.register(CiudadResource())
emisiones.register(MedioResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'adkiller.views.home', name='home'),
    # url(r'^adkiller/', include('adkiller.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/exportar_programas', exportar_programas),
    url(r'^api/exportar_marcas', exportar_marcas),
    (r'^api/', include(emisiones.urls)),
    (r'^app/', include('adkiller.app.urls')),
    (r'^decos/', include('adkiller.decos.urls')),
    (r'^material/', include('adkiller.material.urls')),
    (r'^home/', include('adkiller.home.urls')),
    (r'^social/', include('adkiller.social.urls')),
    (r'^filtros/', include('adkiller.filtros.urls')),
    (r'^informes/', include('adkiller.informes.urls')),
    (r'^usuarios/', include('adkiller.usuarios.urls')),
    (r'^adtrack/', include('adkiller.adtrack.urls')),
    (r'^control/', include('adkiller.control.urls')),
    (r'^apis/', include('adkiller.apis.urls')),
    (r'^media_map/', include('adkiller.media_map.urls')),
    url(r'^$', root, name='root'),
    (r'^autocomplete/', include('autocomplete_light.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',  {'authentication_form': AuthForm}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    (r'^accounts/', include('django.contrib.auth.urls')),
    (r'^accounts/register/$','adkiller.usuarios.views.register'),
    (r'^estado_server/(?P<server>\w+)/','adkiller.app.views.estado_server'),
    (r'^estado_server/','adkiller.app.views.estado_servers'),
    (r'^accounts/register_ok/(?P<usuario>\d+)/','adkiller.usuarios.views.register_ok'),
    (r'^dowser/', include('django_dowser.urls')),

    (r'^thankyou/', direct_to_template, {'template': 'thankyou_page.html','extra_context':{'settings':settings}}),
    (r'^propuesta/', direct_to_template, {'template': 'landing_propuesta.html','extra_context':{'settings':settings}}),
    (r'^accounts/login_demo/$', 'django.contrib.auth.views.login',{'template_name': 'registration/login_demo.html', 'authentication_form': AuthForm, 'extra_context':{'settings':settings}}),

    # archivos especiales
    (r'^jwplayer/jwplayer\.js$', 'django.views.generic.simple.redirect_to', {'url': '/static/js/player/jwplayer.js', 'permanent': True}),
    (r'^jwplayer/jwplayer\.html5\.js$', 'django.views.generic.simple.redirect_to', {'url': '/static/js/player/jwplayer.html5.js', 'permanent': True}),
    (r'^jwplayer/jwplayer\.flash\.swf$', 'django.views.generic.simple.redirect_to', {'url': '/static/js/player/jwplayer.flash.swf', 'permanent': True}),
    (r'^googledae215d9eaff8abb\.html$', 'django.views.generic.simple.redirect_to', {'url': '/static/googledae215d9eaff8abb.html'}),
    (r'^google2f37b16a81f0f6e7\.html$', 'django.views.generic.simple.redirect_to', {'url': '/static/google2f37b16a81f0f6e7.html'}),
    (r'^sitemap\.xml$', 'django.views.generic.simple.redirect_to', {'url': '/static/home/sitemap.xml'}),
    (r'^robots\.txt$', 'django.views.generic.simple.redirect_to', {'url': '/static/home/robots.txt'}),
    (r'^htaccess\.txt$', 'django.views.generic.simple.redirect_to', {'url': '/static/home/htaccess.txt'}),
    (r'^ratings/', upload_ratings),



) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    url(r'^mediamap/static/(?P<path>.*)$',  'django.views.static.serve', {'document_root': settings.MEDIAMAP_ROOT}),
]

urlpatterns += staticfiles_urlpatterns()

#Para detectar memory leaks:
#import guppy
#from guppy.heapy import Remote
#Remote.on()


#DEBUG TOOLBAR: ejecutarlo con servidor de desarrollo de django
#DEBUG_TOOLBAR_PATCH_SETTINGS = False
#INTERNAL_IPS = ["174.37.209.218", "127.0.0.1"]
#from django.conf.urls import include, patterns, url
#if settings.DEBUG:
#    import debug_toolbar
#    urlpatterns += patterns('',
#        url(r'^__debug__/', include(debug_toolbar.urls)),
#    )

adkiller/material/models.py
from django.db import models

# Create your models here.

adkiller/material/forms.py
# -*- coding: utf-8 -*-
from django import forms
from adkiller.app.models import Medio
from django.contrib.admin.widgets import AdminTimeWidget, AdminDateWidget
from django.utils import timezone
from django.db.models import Q

medios = Medio.objects.filter(soporte__nombre="TV Aire Interior Básica", publicar=True)

class MultimediaForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(MultimediaForm, self).__init__(*args, **kwargs)
        print 'INIT FORM'
        self.set_angular_attr()

    canal = forms.ModelChoiceField(
        required=True,
        empty_label='No Seleccionado',
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        ),
        label='Medio',
        queryset=medios.order_by('nombre'),
        to_field_name='id',

    )

    fecha = forms.DateField(
        required=True,
        initial=timezone.now(),
        label='Desde Fecha',
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
            }

        )

    )

    programa = forms.ChoiceField(
        #required=True, #Valida Angular
        choices=((None, 'No Seleccionado'),),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                #'disabled': 'disabled'
            }

        )
    )

    def set_angular_attr(self):
        """
            Setea los attr de AngularJs para utilizar en la vista
            :param form: form de la view
            """
        print 'set Angular_attr'
        self.fields['canal'].widget.attrs['ng-click'] = 'multimedia.make_filter()'
        self.fields['canal'].widget.attrs['ng-model'] = 'multimedia.filters.canal'


        # widget desde_fecha
        self.fields['fecha'].widget.attrs['ng-change'] = 'multimedia.make_filter()'
        self.fields['fecha'].widget.attrs['ng-model'] = 'multimedia.filters.fecha'

        #widget programa
        self.fields['programa'].widget.attrs['ng-blur'] = 'multimedia.check_form()'
        self.fields['programa'].widget.attrs['ng-click'] = 'multimedia.check_form()'
        self.fields['programa'].widget.attrs['ng-model'] = 'multimedia.filters.programa'













    # def get_programas_choices(self):
    #     if self.cleaned_data.canal and self.cleaned_data.desde_fecha and self.cleaned_data.hasta_fecha \
    #             and self.cleaned_data.hora_inicio and self.cleaned_data.hora_fin:
    #
    #         medio = Medio.objects.get(id=self.cleaned_data['canal'])
    #         horarios = medio.horarios.filter(
    #             Q(fechaAlta__gte=self.cleaned_data['desde_fecha']) &
    #             Q(fechaAlta__lte=self.cleaned_data['hasta_fecha']) |
    #             Q(vigenciaHasta__gte=self.cleaned_data['desde_fecha']) &
    #             Q(vigenciaHasta__lte=self.cleaned_data['hasta_fecha']),
    #             Q(horaInicio__gte=self.cleaned_data['hora_inicio']) &
    #             Q(horaInicio__lte=self.cleaned_data['hora_fin']) |
    #             Q(horaFin__gte=self.cleaned_data['hora_inicio']) &
    #             Q(horaFin__lte=self.cleaned_data['hora_fin'])
    #         ).values('programa_id', 'programa__nombre')
    #
    #         return [(horario['programa_id'], horario['programa__nombre']) for horario in horarios]
    #     else:
    #         return ((None, 'No Seleccionado'),),

adkiller/material/views.py
from django.http import HttpResponse
from django.views.generic.edit import FormView
from forms import MultimediaForm
from adkiller.app.models import Medio, Horario
import json
import os
import datetime
import urllib2
from django.core.servers.basehttp import FileWrapper
import time
from django.http import HttpResponse as StreamingHttpResponse
from django.db.models import Q

import logging
logger = logging.getLogger(__name__)

# Esto se supone que iria en Settings o en un getter mas dinamico
multimedia_paths = (
    {'path': 'multimedia/ar/Origenes/'},
    {'path': 'multimedia/ar/OrigenesCortados/'}
)
archivos_disponibles = []

class MainView(FormView):
    form_class = MultimediaForm
    template_name = 'multimedia.html'
    success_url = '/'

    def __init__(self, *args, **kwargs):
        super(MainView, self).__init__(*args, **kwargs)

    def get(self, request, *args, **kwargs):

        ajax_actions = {
            'get_programas': self._ajax_get_programas,
        }

        if request.is_ajax():
            return ajax_actions[request.GET['action']](json.loads(request.GET['params']))

        return super(MainView, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        form.fields['programa'].choices = [(horario.id, horario.programa.nombre) for horario in
                                           self._get_horarios(request.POST)]
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        f_medio_id = form.cleaned_data['canal'].id
        f_fecha = form.cleaned_data['fecha']
        f_programa_id = form.cleaned_data['programa']

        archivos = self._get_archivos_disponibles(f_fecha, f_medio_id,f_programa_id)

        if archivos:
            data_to_return = {
                'error': {
                    'error_code': 0,
                },
                'data': list(archivos)
            }
        else:
            data_to_return = {
                'error': {
                    'error_code': 1,
                    'error_message': 'No hay archivos disponibles. Verifique filtros.'
                }
            }

        return HttpResponse(json.dumps(data_to_return), content_type="application/json")

    def _ajax_get_programas(self, params):
        """
            Retorna programas filtrando por parametros enviados
            :param params: parametros que pasan desde el GET
            """
        horarios = self._get_horarios(params)
        if horarios:
            data_to_return = {
                'error': {
                    'error_code': 0,
                },
                'data': [{'id': h.id, 'programa__nombre': h.programa.nombre} for h in horarios]
            }

        else:
            data_to_return = {
                'error': {
                    'error_code': 1,
                    'error_message': '0 objetos recuperados'
                }
            }

        return HttpResponse(json.dumps(data_to_return), content_type="application/json")

    def _get_horarios(self, params=None, medio_id=None, fecha=None):

        horarios_list = []

        #params de Query
        f_medio_id = medio_id if medio_id else params['canal']
        f_fecha = fecha if fecha else params['fecha']

        if not type(f_fecha) is datetime.date:
            f_fecha = datetime.datetime.strptime(f_fecha, '%d/%m/%Y')
        f_day = f_fecha.weekday()
        f_day = (f_day + 1) % 7

        medio = Medio.objects.get(id=f_medio_id)
        horarios = medio.horarios_de_una_fecha(f_fecha)

        for horario in horarios:
            horarios_list.append(horario)
                #{
                #'programa_id': horario.programa_id,
                #'programa__nombre': horario.programa.nombre,
                #'dias': horario.dias,
                #})

        return horarios_list

    def _get_archivos_disponibles(self, fecha=None, medio_id=None, f_horario_id=None):
        """
        Retorna lista de archivos disponibles con los parametros recibidos.
        :param medio_id: filtro id de Medio
        :param desde_fecha: filtro Desde fecha
        :param hasta_fecha: filtro Hasta Fecha
        :param hora_inicio: filtro Hora Inicio
        :param hora_fin: filtro Hora Fin
        :param horario_id: filtro id horario
        :return: lista de dct con definicion de archivos [{url, file_name},{url, file_name}}]
        """
        archivos_disponibles = []
        horarios = []
        file_id = 0
        f_fecha = fecha

        if not type(f_fecha) is datetime.date:
            f_fecha = datetime.datetime.strptime(f_fecha, '%d/%m/%Y')

        f_day = f_fecha.weekday()    # 0=Lunes, 1=Martes,etc
        f_day = (f_day + 1) % 7

        medio = Medio.objects.get(id=medio_id)

        for horario in Horario.objects.filter(id=f_horario_id):
            for folder in multimedia_paths:

                url = medio.server_grabacion.url
                puerto = medio.server_grabacion.puerto_http
                print 'parsing'


                desde = medio.dvr + "_" + str(medio.canal) + "_" + datetime.datetime.strftime(fecha, '%Y%m%d') + "_"
                hasta = desde 


                url = 'http://{0}:{1}/adtrack/listar_videos.php?folder={2}&desde={3}&hasta={4}'.format(url, puerto, folder['path'], desde, hasta)
                print url
                try:
                    html_to_parse = urllib2.urlopen(url).read()
                except urllib2.URLError as e:
                    html_to_parse = ''
                    logger.error('urllib2.URLError: %s' % e)
                print 'Fin_parsing'
                for link in str(html_to_parse).split("\n"):
                    f = link.split("/")[-1]

                    if len(f.split('.')) > 1 and len(f.split('_')) < 5:  # si es con extension
                        file_name = f.split('.')[0]
                        file_extension = f.split('.')[1]
                        file_params = file_name.split('_')
                        file_medio_dvr = file_params[0]
                        file_medio_canal = int(file_params[1])
                        file_date = datetime.datetime.strptime(file_params[2], '%Y%m%d').date()
                        file_time = datetime.datetime.strptime(file_params[3], '%H%M%S').time()

                        if (horario.horaInicio <= file_time <= horario.horaFin):

                            file_action = '/material/download/{0}&{1}&{2}&{3}'.format(medio.server_grabacion.puerto_http,
                                                                            medio.server_grabacion.url.replace('.', '%2E'),
                                                                            folder['path'].replace('/', '%2F'),
                                                                            f.replace('.', '%2E'))

                            archivo_disponible = {
                                'file_server': medio.server_grabacion.url,
                                'file_port': medio.server_grabacion.puerto_http,
                                'file_folder': folder['path'],
                                'file_name_clean': clean_name(f),
                                'file_name': f,
                                'file_id': file_id,
                                'file_action': file_action
                            }

                            archivos_disponibles.append(archivo_disponible)
                            file_id += 1

        return archivos_disponibles

def clean_name(name):
    start = name.rfind("_")
    end = name.rfind(".")
    name = name[start+1:end-2]
    name = name[:2]+":"+name[2:]+" hs"
    return name

def stream_generator(url, buffer=8192):
    sock = urllib2.urlopen(url)
    while True:
        content = sock.read(buffer)
        if not content: break
        yield content


def download_file(request, params):

    file_server = params.split('&')[1].replace('%2E', '.')
    port = params.split('&')[0]
    file_folder = params.split('&')[2].replace('%2F', '/')
    file_name = params.split('&')[3].replace('%2E', '.')

    url = 'http://{0}:{1}/{2}/{3}'.format(file_server, port, file_folder, file_name)
    print url
    #response = StreamingHttpResponse(stream_generator(url), content_type="video/x-msvideo")
    #response['Content-Disposition'] = "filename='%s'" % file_name

    response = StreamingHttpResponse(stream_generator(url), mimetype='application/force-download')
    response['Content-Disposition'] = "attachent; filename='%s'" % file_name

    return response

adkiller/material/templates/multimedia.html
<!DOCTYPE html>
{%load staticfiles%}
<html ng-app="infoxel_multimedia">
<head lang="en">
    <meta charset="UTF-8">
    <title>Material de Infoxel</title>
    <script src= "{%static "js/lib/jquery-1.11.1.min.js" %}" ></script>
    <script src= "{%static "lib/bootstrap/js/bootstrap.min.js" %}" ></script>
    <script src= "{%static "lib/angular-1.2.21/angular.js" %}" ></script>	
    <script src= "{%static "lib/angular-1.2.21/angular-cookies.js" %}" ></script>
	
    <script src= "{%static "js/material.js" %}" ></script>


	<link rel="stylesheet" href="{%static "lib/bootstrap/css/bootstrap.css" %}">
	<link rel="stylesheet" href="{%static "css/material.css" %}">



    <script src="{% static "lib/bootstrap-datepicker/js/bootstrap-datepicker.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "lib/bootstrap-datepicker/css/datepicker.css" %}" />
      

	<script>
	   var urlPostForm ='/material/'; 
        $(document).ready(function() {
    	   $('#id_fecha').datepicker({
               'format': 'dd/mm/yyyy',
    	       'autoclose': true,
    	       'orientation': 'top',
    	   });
        });
	</script>
    
    <style>
		.div-file:hover{cursor: pointer;}
    </style>
</head>
<body ng-controller="MultimediaController as multimedia">
	
	<div class="container">

		<div id="logo" class="row" style="margin-top:35px;">
			<div class="col-md-1">
				<img class="responsive" src="{%static "img/logo.png" %}">
			</div>

			<div class="col-md-5 col-lg-4">
				<div class="panel panel-default">
				  	<div class="panel-heading text-center">
				  		Búsqueda
				  	</div>
				  	<div class="panel-body">

					<form  id="multimedia_form" onsubmit="return  false;" ng-submit="multimedia.post_multimedia_form()">
			    		{%csrf_token%}

						<div class="form-group search-form-item">
							<div class="input-group col-xs-12">
								<div class="col-md-3 col-sm-2">
									<label style="line-height: 30px;" for="id_canal">Canal</label>
								</div>
								<div class="col-md-9 col-sm-10" ng-disble="true">
									{{form.canal}}
								</div>
							</div>
						</div>


						<div class="form-group search-form-item">
							<div class="input-group col-xs-12">
								<div class="col-md-3 col-sm-2">
									<label style="line-height: 30px;" for="id_fecha">Fecha</label>
								</div>
								<div class="col-md-9 col-sm-10" ng-disble="true">
									{{form.fecha}}
								</div>
							</div>
						</div>


						<div class="form-group search-form-item">
							<div class="input-group col-xs-12">
								<div class="col-md-3 col-sm-2">
									<label style="line-height: 30px;" for="id_programa">Programa</label>
								</div>
								<div class="col-md-9 col-sm-10">
									{{form.programa}}
								</div>
							</div>
						</div>

						<div class="row text-center" >
							<button ng-disabled="multimedia.post_disabled || multimedia_form.$invalid" type="submit" class="btn btn-large submit btn-danger"><i class="glyphicon glyphicon-search"></i> Buscar</button>
						</div>
			    		
					</form>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-7">
				
				<div class="panel panel-default">
				  <div class="panel-heading text-center"><i class="glyphicon glyphicon-th-list"></i> Archivos Disponibles</div>
				  <div class="panel-body" style="min-height: 214px;">
				    <div ng-hide="multimedia.archivos_disponibles.length" style="color:#999; text-align: center; padding: 17px 30px 18px;">
				    	<h4>Instrucciones</h4>
				    	<p>Seleccione un canal, una fecha y un programa. Presione el botón "Buscar" para mostrar una lista de archivos disponibles</p>
				    	<p>
				    </div>
					<div ng-show="multimedia.archivos_disponibles.length">
						<div class="col-lg-4 col-md-6 col-sm-4 col-sm-offset-0 col-xs-6" ng-repeat="archivo in multimedia.archivos_disponibles" style="margin-top:5px;">
							<div class="input-group input-group-lg">

							  	<span class="input-group-addon" id="basic-addon1"><i class="glyphicon glyphicon-file" aria-hidden="true"></i> {$archivo.file_name_clean$}</span>
							  	<span class="input-group-btn">
									<!--button type="button" class="btn btn-inv btn-secondary btn-large" aria-label="right Align"-->
    									    <a href="{$archivo.file_action$}" class="btn btn-inv btn-secondary btn-large" aria-label="right Align">
										<span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
									    </a>
									<!--/button-->
								</span>
							</div>

						</div>
					</div>

				    <div ng-show="(!multimedia.archivos_disponibles.length) && multimedia.error_message"  class="alert alert-danger" role="alert">
				      <strong >Atención</strong> {$multimedia.error_message$}
				    </div>

				  </div>
				</div>

			</div>
		</div>
	</div>


	<script>
	 	
	 	var tag = '<option ng-show="multimedia.programas.length" ng-repeat="programa in multimedia.programas" value="{$programa.id$}">{$programa.programa__nombre$}</option>'
		$('#id_programa').append(tag);

		 
	</script>


	<div id="asyncLoader" style="position:fixed; z-index:1500; right:5px; top:5px;" ng><span class="label label-primary" ng-show="multimedia.ajax.is_loading">{$multimedia.ajax.message$}</span></div>

	<div id="overlayLoader" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: #000; filter:alpha(opacity=50);-moz-opacity:0.5; -khtml-opacity: 0.5; opacity: 0.5; z-index: 1499;" ng-show="multimedia.ajax.block_ui"> </div>

</body>
</html>